version: '2'

services:
  ldap:
    image: bitnami/openldap
    ports:
      - 3389:3389
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=a_great_password
      - LDAP_USERS=a
      - LDAP_PASSWORDS=a
      - LDAP_ROOT=dc=local,dc=com
      - LDAP_PORT_NUMBER=3389
