version: '2'

services:
  ldap:
    image: bitnami/openldap:latest
    ports:
      - 1389:1389
      - 1636:1636
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=a_great_password
      - LDAP_USERS=a
      - LDAP_PASSWORDS=a
      - LDAP_ROOT=dc=local,dc=com
      - LDAP_PORT_NUMBER=1389
      - LDAP_ENABLE_TLS=yes
      - LDAP_LDAPS_PORT_NUMBER=1636
      - LDAP_TLS_VERIFY_CLIENT=try
      - LDAP_TLS_CERT_FILE=/opt/bitnami/openldap/certs/openldap.crt
      - LDAP_TLS_KEY_FILE=/opt/bitnami/openldap/certs/openldap.key
      - LDAP_TLS_CA_FILE=/opt/bitnami/openldap/certs/openldapCA.crt
    volumes:
      - ./Tests/certs:/opt/bitnami/openldap/certs
