version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - .:/workspace:cached
    
    network_mode: service:ldap

    command: /bin/sh -c "while sleep 1000; do :; done"